<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="1" skipped="2" tests="8" time="0.165" timestamp="2024-06-11T10:46:19.749871" hostname="MRaghavendraHP2"><testcase classname="test_sample2_copy.test_samplefile2_copy" name="test_fun" time="0.002" /><testcase classname="test_sample2_copy.test_samplefile2_copy.TestA" name="test_method1" time="0.001" /><testcase classname="test_sample2_copy.test_samplefile2_copy.TestA" name="test_method2" time="0.002" /><testcase classname="test_sample2_copy.test_samplefile2_copy.TestA" name="test_method3" time="0.001" /><testcase classname="test_sample2_copy.test_samplefile2_copy.TestA" name="test_method4" time="0.001" /><testcase classname="test_sample2_copy.test_samplefile2_copy.TestA" name="test_method5" time="0.001"><skipped type="pytest.skip" message="unconditional skip">C:\Users\ragha\My Drive (raghavendramorisetty@gmail.com)\RMALL\sem4\NARESHIT\Tools git docker Testing by suman sir\Git-code-practice\Git-practice-sumansir\Git-practice-suman-sir2\test_sample2_copy\test_samplefile2_copy.py:19: unconditional skip</skipped></testcase><testcase classname="test_sample2_copy.test_samplefile2_copy.TestA" name="test_method6" time="0.001"><failure message="assert 1 == 2">self = &lt;test_samplefile2_copy.TestA object at 0x00000141DAB694F0&gt;

    def test_method6(self):
&gt;       assert 1==2
E       assert 1 == 2

test_sample2_copy\test_samplefile2_copy.py:23: AssertionError</failure></testcase><testcase classname="test_sample2_copy.test_samplefile2_copy.TestA" name="test_method7" time="0.001"><skipped type="pytest.xfail" message="" /></testcase></testsuite></testsuites>